//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManager.Repository
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.ShipToes = new HashSet<ShipTo>();
        }
    
        public int CustomerId { get; set; }
        [Required(ErrorMessage = "Please enter customer name"), MaxLength(50)]
        [Display(Name ="Customer Name:")]
        public string CustomerName { get; set; }
        [StringLength(10, ErrorMessage ="SHould be less than 30")]
        public string ContactName { get; set; }
        public string ContactPhoneNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipTo> ShipToes { get; set; }
    }
}
