//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManager.Repository
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ShipTo
    {
        public int ShipToId { get; set; }
        public int CustomerId { get; set; }
        [Required]
        [StringLength(50)]
        public string ShipToAddress { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
